#!/bin/bash

set -euo pipefail

printf -- "--- :buildkite: Setting image env\n"

export TF_VAR_release_s3_bucket
export TF_VAR_release_s3_key

TF_VAR_release_s3_bucket="com.codeclimate.hestia"
TF_VAR_release_s3_key="release/package_$BUILDKITE_BUILD_NUMBER.zip"

printf "TF_VAR_release_s3_bucket=%s\n" "$TF_VAR_release_s3_bucket"
printf "TF_VAR_release_s3_key=%s\n" "$TF_VAR_release_s3_key"
